# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/gui/ui/window.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 650))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 650))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(240, 410, 751, 151))
        self.groupBox.setObjectName("groupBox")
        self.cbClear = QtWidgets.QCheckBox(self.groupBox)
        self.cbClear.setGeometry(QtCore.QRect(10, 30, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbClear.setFont(font)
        self.cbClear.setObjectName("cbClear")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 80, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lbShow = QtWidgets.QLabel(self.groupBox)
        self.lbShow.setGeometry(QtCore.QRect(100, 80, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbShow.setFont(font)
        self.lbShow.setObjectName("lbShow")
        self.btnStart = QtWidgets.QPushButton(self.groupBox)
        self.btnStart.setGeometry(QtCore.QRect(530, 30, 201, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnStart.setFont(font)
        self.btnStart.setObjectName("btnStart")
        self.btnSeek = QtWidgets.QPushButton(self.groupBox)
        self.btnSeek.setGeometry(QtCore.QRect(330, 30, 180, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSeek.sizePolicy().hasHeightForWidth())
        self.btnSeek.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSeek.setFont(font)
        self.btnSeek.setObjectName("btnSeek")
        self.btnClearOnly = QtWidgets.QPushButton(self.groupBox)
        self.btnClearOnly.setGeometry(QtCore.QRect(530, 90, 201, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnClearOnly.setFont(font)
        self.btnClearOnly.setObjectName("btnClearOnly")
        self.gbBodyData = QtWidgets.QGroupBox(self.centralwidget)
        self.gbBodyData.setGeometry(QtCore.QRect(240, 20, 751, 371))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gbBodyData.setFont(font)
        self.gbBodyData.setObjectName("gbBodyData")
        self.gbTargets = QtWidgets.QGroupBox(self.gbBodyData)
        self.gbTargets.setGeometry(QtCore.QRect(10, 240, 501, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gbTargets.setFont(font)
        self.gbTargets.setObjectName("gbTargets")
        self.lbKCal = QtWidgets.QLabel(self.gbTargets)
        self.lbKCal.setGeometry(QtCore.QRect(10, 30, 61, 21))
        self.lbKCal.setObjectName("lbKCal")
        self.cbEeTarget = QtWidgets.QComboBox(self.gbTargets)
        self.cbEeTarget.setGeometry(QtCore.QRect(80, 30, 101, 22))
        self.cbEeTarget.setObjectName("cbEeTarget")
        self.lbSteps = QtWidgets.QLabel(self.gbTargets)
        self.lbSteps.setGeometry(QtCore.QRect(320, 30, 71, 20))
        self.lbSteps.setObjectName("lbSteps")
        self.cbStepTarget = QtWidgets.QComboBox(self.gbTargets)
        self.cbStepTarget.setGeometry(QtCore.QRect(390, 30, 91, 22))
        self.cbStepTarget.setObjectName("cbStepTarget")
        self.gbBDay = QtWidgets.QGroupBox(self.gbBodyData)
        self.gbBDay.setGeometry(QtCore.QRect(10, 40, 501, 81))
        self.gbBDay.setObjectName("gbBDay")
        self.lbBirthday = QtWidgets.QLabel(self.gbBDay)
        self.lbBirthday.setGeometry(QtCore.QRect(10, 50, 91, 20))
        self.lbBirthday.setObjectName("lbBirthday")
        self.lbDay = QtWidgets.QLabel(self.gbBDay)
        self.lbDay.setGeometry(QtCore.QRect(100, 30, 31, 21))
        self.lbDay.setObjectName("lbDay")
        self.lbMonth = QtWidgets.QLabel(self.gbBDay)
        self.lbMonth.setGeometry(QtCore.QRect(170, 30, 52, 21))
        self.lbMonth.setObjectName("lbMonth")
        self.lbYear = QtWidgets.QLabel(self.gbBDay)
        self.lbYear.setGeometry(QtCore.QRect(240, 30, 52, 20))
        self.lbYear.setObjectName("lbYear")
        self.cbBDayDay = QtWidgets.QComboBox(self.gbBDay)
        self.cbBDayDay.setGeometry(QtCore.QRect(100, 50, 51, 22))
        self.cbBDayDay.setObjectName("cbBDayDay")
        self.cbBDayMonth = QtWidgets.QComboBox(self.gbBDay)
        self.cbBDayMonth.setGeometry(QtCore.QRect(170, 50, 51, 22))
        self.cbBDayMonth.setObjectName("cbBDayMonth")
        self.cbBDayYear = QtWidgets.QComboBox(self.gbBDay)
        self.cbBDayYear.setGeometry(QtCore.QRect(240, 50, 71, 22))
        self.cbBDayYear.setObjectName("cbBDayYear")
        self.gbHeightWeight = QtWidgets.QGroupBox(self.gbBodyData)
        self.gbHeightWeight.setGeometry(QtCore.QRect(10, 150, 501, 61))
        self.gbHeightWeight.setObjectName("gbHeightWeight")
        self.lbHeight = QtWidgets.QLabel(self.gbHeightWeight)
        self.lbHeight.setGeometry(QtCore.QRect(10, 30, 111, 21))
        self.lbHeight.setObjectName("lbHeight")
        self.cbHeight = QtWidgets.QComboBox(self.gbHeightWeight)
        self.cbHeight.setGeometry(QtCore.QRect(120, 30, 81, 22))
        self.cbHeight.setObjectName("cbHeight")
        self.lbWeight = QtWidgets.QLabel(self.gbHeightWeight)
        self.lbWeight.setGeometry(QtCore.QRect(280, 30, 101, 21))
        self.lbWeight.setObjectName("lbWeight")
        self.cbWeight = QtWidgets.QComboBox(self.gbHeightWeight)
        self.cbWeight.setGeometry(QtCore.QRect(390, 30, 91, 22))
        self.cbWeight.setObjectName("cbWeight")
        self.gbOthers = QtWidgets.QGroupBox(self.gbBodyData)
        self.gbOthers.setGeometry(QtCore.QRect(530, 40, 201, 261))
        self.gbOthers.setObjectName("gbOthers")
        self.lbSmoker = QtWidgets.QLabel(self.gbOthers)
        self.lbSmoker.setGeometry(QtCore.QRect(10, 160, 91, 21))
        self.lbSmoker.setObjectName("lbSmoker")
        self.cbSmoker = QtWidgets.QComboBox(self.gbOthers)
        self.cbSmoker.setGeometry(QtCore.QRect(110, 160, 81, 22))
        self.cbSmoker.setObjectName("cbSmoker")
        self.lbHand = QtWidgets.QLabel(self.gbOthers)
        self.lbHand.setGeometry(QtCore.QRect(10, 100, 91, 21))
        self.lbHand.setObjectName("lbHand")
        self.cbHand = QtWidgets.QComboBox(self.gbOthers)
        self.cbHand.setGeometry(QtCore.QRect(110, 100, 81, 22))
        self.cbHand.setObjectName("cbHand")
        self.lbSex = QtWidgets.QLabel(self.gbOthers)
        self.lbSex.setGeometry(QtCore.QRect(10, 40, 91, 21))
        self.lbSex.setObjectName("lbSex")
        self.cbSex = QtWidgets.QComboBox(self.gbOthers)
        self.cbSex.setGeometry(QtCore.QRect(110, 40, 81, 22))
        self.cbSex.setObjectName("cbSex")
        self.btnBodyData = QtWidgets.QPushButton(self.gbBodyData)
        self.btnBodyData.setGeometry(QtCore.QRect(10, 320, 501, 41))
        self.btnBodyData.setObjectName("btnBodyData")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(569, 580, 421, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnClose.setFont(font)
        self.btnClose.setObjectName("btnClose")
        self.btnSwitch = QtWidgets.QPushButton(self.centralwidget)
        self.btnSwitch.setGeometry(QtCore.QRect(240, 580, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSwitch.setFont(font)
        self.btnSwitch.setObjectName("btnSwitch")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 221, 371))
        self.groupBox_2.setObjectName("groupBox_2")
        self.teHints = QtWidgets.QTextEdit(self.groupBox_2)
        self.teHints.setGeometry(QtCore.QRect(5, 25, 211, 341))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.teHints.setFont(font)
        self.teHints.setReadOnly(True)
        self.teHints.setObjectName("teHints")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btnStart.clicked.connect(MainWindow.Proc_Start)
        self.btnSeek.clicked.connect(MainWindow.Seek)
        self.btnClearOnly.clicked.connect(MainWindow.ClearOnly)
        self.btnClose.clicked.connect(MainWindow.Proc_End)
        self.btnSwitch.clicked.connect(MainWindow.SwitchLanguage)
        self.btnBodyData.clicked.connect(MainWindow.PushToBM)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FreeTheBodyM"))
        self.groupBox.setTitle(_translate("MainWindow", "BodyMedia"))
        self.cbClear.setText(_translate("MainWindow", "Speicher nach dem Auslesen loeschen"))
        self.label.setText(_translate("MainWindow", "Armband:"))
        self.lbShow.setText(_translate("MainWindow", "TextLabel"))
        self.btnStart.setText(_translate("MainWindow", "BodyMedia\n"
"auslesen"))
        self.btnSeek.setText(_translate("MainWindow", "Armband nicht\n"
"gefunden?\n"
"Erneut Suchen"))
        self.btnClearOnly.setText(_translate("MainWindow", "BodyMedia aktivieren"))
        self.gbBodyData.setTitle(_translate("MainWindow", "Koerperdaten"))
        self.gbTargets.setTitle(_translate("MainWindow", "Ziele"))
        self.lbKCal.setText(_translate("MainWindow", "Kalorien:"))
        self.lbSteps.setText(_translate("MainWindow", "Schritte:"))
        self.gbBDay.setTitle(_translate("MainWindow", "Geburtstag"))
        self.lbBirthday.setText(_translate("MainWindow", "Geburtstag:"))
        self.lbDay.setText(_translate("MainWindow", "Tag"))
        self.lbMonth.setText(_translate("MainWindow", "Monat"))
        self.lbYear.setText(_translate("MainWindow", "Jahr"))
        self.gbHeightWeight.setTitle(_translate("MainWindow", "Groesse und Gewicht"))
        self.lbHeight.setText(_translate("MainWindow", "Groesse in cm:"))
        self.lbWeight.setText(_translate("MainWindow", "Gewicht in kg:"))
        self.gbOthers.setTitle(_translate("MainWindow", "Sonstiges"))
        self.lbSmoker.setText(_translate("MainWindow", "Raucher:"))
        self.lbHand.setText(_translate("MainWindow", "Haender:"))
        self.lbSex.setText(_translate("MainWindow", "Geschlecht:"))
        self.btnBodyData.setText(_translate("MainWindow", "Aktuell eingestellte Koerperdaten auf das BodyMedia uebertragen"))
        self.btnClose.setText(_translate("MainWindow", "Beenden"))
        self.btnSwitch.setText(_translate("MainWindow", "Sprache umschalten deutsch / englisch\n"
"Switch language german / english"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Hinweise"))

